### PR TITLE
Remove lotion's gci-* functions

### PR DESCRIPTION
**Pull request by pinkiebell**
So that we get rid of peer-channel

Related #111

### CODE REVIEW

**Comment by pinkiebell** [comment]
@troggy Damn it 😆 . Hadn't a change to test the node because of all the errors mentioned in slack.
I take a deeper look, we probably still can remove these dependencies somehow.
Do you know if any part is requesting the genesis file from the http server?

**Comment by troggy** [comment]
> Do you know if any part is requesting the genesis file from the http server?

Genesis can be read via tendermint RPC, so this is not the problem.


However, [machine gun](https://github.com/leapdao/leap-node/blob/master/tools/machine-gun.js) uses `/state` endpoint to get unspents and balance (kind of hack, but yet used for now)

**Comment by johannbarbie** [comment]
> However, [machine gun](https://github.com/leapdao/leap-node/blob/master/tools/machine-gun.js) uses `/state` endpoint to get unspents and balance (kind of hack, but yet used for now)

the sniper rifle here does the same thing like machine gun, but using the json-rpc: https://github.com/leapdao/leap-sniper-rifle/blob/master/src/index.js#L35
the only place where machine-gun is needed are integration tests, i think we could easily replace it.

**Comment by pinkiebell** [comment]
merged into #141

**Pull request closed without merging**
