### PR TITLE
Adds support for Node version >=12

### LINKED ISSUE #346: support "yarn global add leap-node" with node -v >= 12
# Bounty Description:

when running  `yarn global add leap-node` the expected out is `successful install`. With node versions >= 12. the following output is observed:
```
...
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/johba/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/johba/.nvm/versions/node/v12.13.0/bin/node" "/Users/johba/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/johba/.config/yarn/global/node_modules/scrypt
``` 

## Scope

- fix code or dependencies so that install with node -v > 12 passes successfully on linux and OSX

## Gain for the project

- support broader stack and reduce frustration during installation

### PR DESCRIPTION
**Pull request by agbilotia1998**
Fixes #346

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@simonweniger please review, adding this comment in case auto review request is not created. Thanks :)

**Comment by simonweniger** [comment]
@troggy can you review this ?

**Comment by agbilotia1998** [comment]
@simonweniger I've submitted this as work on Gitcoin, please have a look. Thanks :)

**Comment by simonweniger** [comment]
@agbilotia1998 payout done, thank you for the contribution. We would love to have you as a contributor. So pleas check other available bountys at [leapdao.org/earn](https://leapdao.org/earn/). You also will recive LeapTokens as a reputation payment, so make sure you aktivate them in your wallet. This is the Leap Token adress: 0x78230e69d6e6449db1e11904e0bd81c018454d7a

**Comment by agbilotia1998** [comment]
I've added Leap Token to my account, sure I'll have a look at other bounties as well. Thanks :)

**Comment by troggy** [comment]
I've found one side effect for using leap-node with node 12.

leap-node uses `keccak` package via ethereumjs-util package. This package supports native builds (via node-gyp) and falls back to pure JS implementation if it fails to compile native build on install. What I've noticed is that `keccak` native build always fails for node 12, so pure js implementation will always be used. I'm not sure what are implications of this, probably only possible performance degradation?

Related issue: https://github.com/cryptocoinjs/keccak/issues/10 (resolved in keccak@2.1.0, but latest ethereumjs-util still uses older version)

/cc @TheReturnOfJan

**Comment by troggy** [comment]
How to check:

if your installation uses js implementation of kecak you will see this on startup: `Keccak bindings are not compiled. Pure JS implementation will be used.`

**Pull request merged**
