### PR TITLE
Remove readonly option from config

### LINKED ISSUE #306: Remove "readonly validator" feature
# Bounty

We [decided](https://leapdao.slack.com/archives/CFQH2UH3Q/p1562066239004000?thread_ts=1561724029.001100&cid=CFQH2UH3Q) not to use anymore because of mainnet [incident](https://leapdao.org/blog/mainnet-postmortem/).

It is not used anymore on both testnet and mainnet, so let's remove the flag from the code

## Scope
- remove `readonly` flag and related code from the leap-node
- remove `SetReadonly` thing and related code from Leap Tendermint fork
- make sure everything is working

## Deliverables

- updated leap-node code
- updated unit tests in leap-node
- updated tendermint fork code
- new tendermint fork release, used in leap-node

## Gain for the project

cleaner code, less tech debt, easier to pull tendermint upstream

### Publicly visible delivery

🤷‍♂️

## Roles
bounty gardener: @troggy / 40 DAI
bounty worker: @TimDaub / 75%
bounty reviewer: name / 25%

### PR DESCRIPTION
**Pull request by TimDaub**
Fixes #306

## Questions

- Here https://github.com/leapdao/leap-node/compare/fix/remove-readonly-node-config-option?expand=1#diff-786c9ee7cb87a989994653f4a23150a6L20 and here https://github.com/leapdao/leap-node/compare/fix/remove-readonly-node-config-option?expand=1#diff-8372d553eb3845a04d491ab410b2620aL44 we're removing `nodeConfig` as it wasn't used by any code anymore. Is that fine?
- I removed a whole unit test [here](https://github.com/leapdao/leap-node/compare/fix/remove-readonly-node-config-option?expand=1#diff-4409efee4e61b37ee80315e273018e4fL191). It just checks that there's no period submitted for a readonly node, correct? So we can safely remove it?  

## TODOs:

- [x] Make changes on leapdao/tendermint too
- [x] Release new version of leapdao/tendermint and add it as a dependency here

### CODE REVIEW

**Comment by sunify** [comment]
Do not forget to update tendermint version (hashes) in https://github.com/leapdao/leap-node/tree/master/lotion/bin

**Comment by TimDaub** [comment]
> Do not forget to update tendermint version (and hashes) in https://github.com/leapdao/leap-node/tree/master/lotion/bin

Yup. I'll change those as soon as we have a newly release version of leapdao/tendermint!

**Comment by TimDaub** [comment]
https://github.com/leapdao/tendermint/pull/9 was approved and merged. Will release a new version and update this PR. Then we can have it merged.

**Comment by TimDaub** [comment]
503297e219c2314099bc4723536088afd4253701 updates to the latest leapdao/tendermint release.

**Pull request merged**
