### PR TITLE
[💥breaking] remove useless tx encoding in abci

### PR DESCRIPTION
**Pull request by pinkiebell**
Next breaking changes for leap-node

- Remove Tx encoding in abci, it's useless ***BREAKING CHANGE***
- TODO Use `secp256k1` ?

### CODE REVIEW

**Comment by troggy** [comment]
@pinkiebell is `broadcast_tx_*` change breaking? Can we merge it separately?

**Comment by troggy** [comment]
merged with master. @pinkiebell pls take a look if the resulting PR is good?

**Comment by pinkiebell** [comment]
@troggy That branch already diverted a bit with my local changes. I roll this up again in smaller chunks ;)

**Comment by pinkiebell** [comment]
@troggy Ah, you already sorted that out. Ok 👍

**Pull request merged**
