### PR TITLE
Fix epochLength update

### LINKED ISSUE #310: Cannot change epoch length
# Bounty

**Given:**
Testnet with two validators and epochLength set to 4.
Governance proposal `setEpochLength(2)` is submitted and finalized.
`EpochLength` event lands on the root chain.
`PoaOperator.epochLength` is changed to 2.

**Expected:**
Epoch length in leap-node's `bridgeState` is changed to 2.

**Actual:**
Epoch length in leap-node's `bridgeState` remains equals to 4. `leap-node:error Unknown epochLength change` error in logs

## Scope

- find and fix a root cause for described issue

## Deliverables

- updated code and tests

## Gain for the project

properly working epochLength setup

### Publicly visible delivery

🤷‍♂ 

## Roles
bounty gardener: @troggy / 30 DAI
bounty worker: @sunify / 80%
bounty reviewer: @iamonuwa + @troggy  / 20%

## Funded by

EF

### PR DESCRIPTION
**Pull request by sunify**
Resolves #310

The problem was with this condition:

https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkEpochLength.js#L15-L20

In replay we already have all events processed by bridgeState, so the check always was false. I think we can safely remove it since we have this check bellow: https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkEpochLength.js#L22-L27

Also, I removed the same check from `checkMinGasPrice`

### CODE REVIEW

**Comment by sunify** [comment]
@iamonuwa have you ran integration tests?

**Comment by troggy** [comment]
Just checked — It solves the problem with EpochLength change at block height 👍

Network still not syncs but because of the different problem: https://github.com/leapdao/leap-node/issues/324. Not related

**Comment by iamonuwa** [comment]
> @iamonuwa have you ran integration tests?

I reviewed the code. And it looks good 🤷‍♂️

**Comment by troggy** [comment]
✅integration tests against this branch and leap-contracts `master`

**Pull request merged**
